import type { Match, Team } from './types';
import { createClient } from './supabase/server';

const team = (row: any): Team | null => row ? { id: row.id, name: row.name, shortName: row.short_name, fifaCode: row.fifa_code, isoCode: row.iso_code, flagUrl: row.flag_url, externalId: row.external_id, isActive: row.is_active } : null;
const match = (row: any): Match => ({ id: row.id, round: row.round, roundOrder: row.round_order, homeTeam: team(row.home_team), awayTeam: team(row.away_team), kickoffAt: row.kickoff_at, lockAt: row.lock_at, stadium: row.stadium, city: row.city, status: row.status, homeScore90: row.home_score_90, awayScore90: row.away_score_90, qualifiedTeamId: row.qualified_team_id, winnerTeamId: row.winner_team_id, loserTeamId: row.loser_team_id, manuallyLocked: row.manually_locked, homeSourceMatchId: row.home_source_match_id, awaySourceMatchId: row.away_source_match_id, homeSourceType: row.home_source_type, awaySourceType: row.away_source_type });
export async function getMatches() { const sb = await createClient(); if (!sb) return []; const { data, error } = await sb.from('matches').select('*, home_team:home_team_id(*), away_team:away_team_id(*)').order('round_order'); if (error) throw error; return (data ?? []).map(match); }
export async function getLeaderboard(limit?: number) { const sb = await createClient(); if (!sb) return []; const { data, error } = await sb.rpc('public_leaderboard'); if (error) throw error; return (data ?? []).slice(0, limit).map((r: any) => ({ position: r.position, participantName: r.participant_name, totalPoints: r.total_points, exactScores: r.exact_scores, outcomes: r.outcomes, qualified: r.qualified, counted: r.counted })); }
export async function getProfile() { const sb = await createClient(); if (!sb) return null; const { data: { user } } = await sb.auth.getUser(); if (!user) return null; const { data } = await sb.from('profiles').select('*').eq('id', user.id).single(); return data; }
export async function getUserPredictions(userId: string) { const sb = await createClient(); if (!sb) return []; const { data, error } = await sb.from('predictions').select('*').eq('user_id', userId); if (error) throw error; return data ?? []; }
